# Generated by Django 4.0 on 2024-03-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundfair', '0003_emailverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=42)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target', models.BigIntegerField()),
                ('deadline', models.DateTimeField()),
                ('amountRaised', models.BigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='campaign_images/')),
                ('donators', models.JSONField(blank=True, default=list)),
                ('donations', models.JSONField(blank=True, default=list)),
                ('isFundingGoalReached', models.BooleanField(default=False)),
                ('isCampaignClosed', models.BooleanField(default=False)),
                ('fundingModel', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('HealthAndMedicine', 'Health and Medicine'), ('EnvironmentAndWildlife', 'Environment and Wildlife'), ('EducationAndResearch', 'Education and Research'), ('PovertyAndHumanServices', 'Poverty and Human Services'), ('ArtsCultureAndHumanities', 'Arts, Culture, and Humanities'), ('ChildrenAndYouth', 'Children and Youth'), ('DisasterReliefAndEmergencyResponse', 'Disaster Relief and Emergency Response'), ('AnimalWelfare', 'Animal Welfare'), ('CommunityAndCivicProjects', 'Community and Civic Projects'), ('TechnologyAndInnovation', 'Technology and Innovation'), ('VeteransAndMilitaryFamilies', 'Veterans and Military Families'), ('HumanRightsAndSocialJustice', 'Human Rights and Social Justice'), ('InternationalAidAndDevelopment', 'International Aid and Development'), ('FaithBasedAndReligious', 'Faith-Based and Religious'), ('SportsAndRecreation', 'Sports and Recreation'), ('MentalHealthAndWellness', 'Mental Health and Wellness')], max_length=50)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
