# Generated by Django 4.0 on 2024-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundfair', '0005_alter_campaign_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.CharField(max_length=42),
        ),
    ]
