# Generated by Django 4.0 on 2024-03-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundfair', '0007_alter_campaign_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target',
            field=models.CharField(max_length=255),
        ),
    ]
